### ISSUE TITLE
Set Up and Configure Keycloak

### ISSUE THREAD

**Issue by Pawel-Mackiewicz** [BankApp-project/bankapp-backend#77]
### Step 1: Set Up and Configure Keycloak

First, you need a running Keycloak instance. The easiest way is with Docker.

1.  **Run Keycloak:**
    Create a `docker-compose.yml` file:
    ```yaml
    version: '3.8'
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:latest
        command: start-dev
        environment:
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
          - "8180:8080"
    ```
    Run it with `docker-compose up`. Keycloak will be available at `http://localhost:8180`.

2.  **Log In and Create a Realm:**
    *   Go to `http://localhost:8180` and click on "Administration Console".
    *   Log in with `admin` / `admin`.
    *   Hover over "Master" in the top-left corner and click "Create Realm".
    *   Name your realm something like `my-app-realm`. A realm is an isolated space for your users and applications.

3.  **Create a Client:**
    A "Client" in Keycloak represents your Spring Boot application.
    *   In your new realm, go to "Clients" and click "Create client".
    *   **Client ID:** `my-spring-boot-app` (this is important, remember it).
    *   Click Next. Keep "Standard flow" enabled.
    *   **Valid Redirect URIs:** This is crucial. It's the URL Keycloak is allowed to redirect to after a successful login. For Spring Boot, the default is `{baseUrl}/login/oauth2/code/{registrationId}`. Enter: `http://localhost:8080/login/oauth2/code/keycloak`
    *   Save the client.

4.  **Get Client Credentials:**
    *   In your new client's settings, go to the "Credentials" tab.
    *   You will see a "Client secret". Copy this value. You will need it later.
