### ISSUE TITLE
(3#) OAuth2(keycloak): Reconfigure Your Spring Boot Security

### ISSUE THREAD

**Issue by Pawel-Mackiewicz** [BankApp-project/bankapp-backend#79]
## Written by LLM
**Expect missing and wrong informations. Verify!**

### Step 3: Reconfigure Your Spring Boot Security

Now, wire up Spring Security to talk to Keycloak.

1.  **Update `pom.xml` Dependencies:**
    Ensure you have the `oauth2-client` and `oauth2-resource-server` starters.
    ```xml
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-oauth2-client</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
    </dependency>
    ```

2.  **Configure `application.yml`:**
    Point Spring Security to your Keycloak realm.

    ```yaml
    spring:
      security:
        oauth2:
          client:
            registration:
              keycloak: # This name must match the redirect URI path segment
                provider: keycloak
                client-id: my-spring-boot-app
                client-secret: YOUR_COPIED_CLIENT_SECRET
                authorization-grant-type: authorization_code
                scope: openid, profile, email
            provider:
              keycloak:
                issuer-uri: http://localhost:8180/realms/my-app-realm # <-- IMPORTANT
          resourceserver:
            jwt:
              issuer-uri: http://localhost:8180/realms/my-app-realm # <-- IMPORTANT
    ```

3.  **Rewrite Your `SecurityConfig.java`:**
    Replace your Basic Auth configuration with the OAuth 2.0 DSL.

    ```java
    import org.springframework.context.annotation.Bean;
    import org.springframework.context.annotation.Configuration;
    import org.springframework.security.config.annotation.web.builders.HttpSecurity;
    import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
    import org.springframework.security.web.SecurityFilterChain;
    import static org.springframework.security.config.Customizer.withDefaults;

    @Configuration
    @EnableWebSecurity
    public class SecurityConfig {

        @Bean
        public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
            http
                .authorizeHttpRequests(authorize -> authorize
                    .requestMatchers("/", "/error").permitAll() // Public pages
                    .anyRequest().authenticated() // All other requests need a user to be logged in
                )
                .oauth2Login(withDefaults()) // Enables the login flow for browsers
                .oauth2ResourceServer(oauth2 -> oauth2.jwt(withDefaults())); // Enables token validation for APIs

            return http.build();
        }
    }
    ```
